[Exports]
"Export Mode" = "byClass"
"Export Style" = "Single file"
"Export Format" = "h5"
"Export Compression" = true
"Export Elements" = true
"Export Data Tables" = false
"Export Data In Memory" = false
"HDF Max Chunk Bytes" = 1048576
"Export Event Log" = true
"Log Results" = true

[Plots]
"Create dynamic plots" = false
"Open plots in browser" = true

[Project]
"Start time" = "2017-01-02 07:00:00.0"
"Simulation duration (min)" = 1440.0
"Loadshape start time" = "2017-01-01 00:00:00.0"
"Step resolution (sec)" = 300.0
"Max Control Iterations" = 100
"Error tolerance" = 0.001
"Control mode" = "Time"
"Disable PyDSS controllers" = false
"Project Path" = "../"
"Simulation Type" = "QSTS"
"Active Project" = "p4uhs0_4"
"Active Scenario" = "p4uhs0_4"
"DSS File" = "Master.dss"
"DSS File Absolute Path" = false
"Return Results" = true
[[Project.Scenarios]]
name = "p4uhs0_4"
post_process_infos = []

[Helics]
"Co-simulation Mode" = true
"Federate name" = "p4uhs0_69"
"Time delta" = 0.01
"Core type" = "tcp_ss"
Uninterruptible = true
"Iterative Mode" = true
"Helics logging level" = 3
"Error tolerance" = 0.001
"Max co-iterations" = 20
Broker = "127.0.0.1"
"Broker port" = 23404

[Frequency]
"Enable frequency sweep" = false
"Fundamental frequency" = 60
"Start frequency" = 1.0
"End frequency" = 15.0
"frequency increment" = 2.0
"Neglect shunt admittance" = false
"Percentage load in series" = 50.0

[Logging]
"Logging Level" = "DEBUG"
"Log to external file" = true
"Display on screen" = true
"Clear old log file" = true

[MonteCarlo]
"Number of Monte Carlo scenarios" = -1
