["PVSystem.pv_load_p4ulv39"]
Control1 = "VVar"
Control2 = "None"
Control3 = "None"
pf = -0.95
pfMin = 0.9
pfMax = 1.05
Pmin = 0
Pmax = 1
uMin = 0.92
uDbMin = 0.967
uDbMax = 1.033
uMax = 1.07
QlimPU = 0.44
PFlim = 0.9
"Enable PF limit" = false
uMinC = 1.06
uMaxC = 1.1
PminVW = 10
VWtype = "Rated Power"
"%PCutin" = 0.1
"%PCutout" = 0.1
Efficiency = 100
Priority = "Var"
DampCoef = 0.8

["PVSystem.pv_load_p4ulv11"]
Control1 = "VVar"
Control2 = "None"
Control3 = "None"
pf = -0.95
pfMin = 0.9
pfMax = 1.05
Pmin = 0
Pmax = 1
uMin = 0.92
uDbMin = 0.967
uDbMax = 1.033
uMax = 1.07
QlimPU = 0.44
PFlim = 0.9
"Enable PF limit" = false
uMinC = 1.06
uMaxC = 1.1
PminVW = 10
VWtype = "Rated Power"
"%PCutin" = 0.1
"%PCutout" = 0.1
Efficiency = 100
Priority = "Var"
DampCoef = 0.8

["PVSystem.pv_load_p4ulv2"]
Control1 = "VVar"
Control2 = "None"
Control3 = "None"
pf = -0.95
pfMin = 0.9
pfMax = 1.05
Pmin = 0
Pmax = 1
uMin = 0.92
uDbMin = 0.967
uDbMax = 1.033
uMax = 1.07
QlimPU = 0.44
PFlim = 0.9
"Enable PF limit" = false
uMinC = 1.06
uMaxC = 1.1
PminVW = 10
VWtype = "Rated Power"
"%PCutin" = 0.1
"%PCutout" = 0.1
Efficiency = 100
Priority = "Var"
DampCoef = 0.8

["PVSystem.pv_load_p4ulv14"]
Control1 = "VVar"
Control2 = "None"
Control3 = "None"
pf = -0.95
pfMin = 0.9
pfMax = 1.05
Pmin = 0
Pmax = 1
uMin = 0.92
uDbMin = 0.967
uDbMax = 1.033
uMax = 1.07
QlimPU = 0.44
PFlim = 0.9
"Enable PF limit" = false
uMinC = 1.06
uMaxC = 1.1
PminVW = 10
VWtype = "Rated Power"
"%PCutin" = 0.1
"%PCutout" = 0.1
Efficiency = 100
Priority = "Var"
DampCoef = 0.8

["PVSystem.pv_load_p4ulv15"]
Control1 = "VVar"
Control2 = "None"
Control3 = "None"
pf = -0.95
pfMin = 0.9
pfMax = 1.05
Pmin = 0
Pmax = 1
uMin = 0.92
uDbMin = 0.967
uDbMax = 1.033
uMax = 1.07
QlimPU = 0.44
PFlim = 0.9
"Enable PF limit" = false
uMinC = 1.06
uMaxC = 1.1
PminVW = 10
VWtype = "Rated Power"
"%PCutin" = 0.1
"%PCutout" = 0.1
Efficiency = 100
Priority = "Var"
DampCoef = 0.8

["PVSystem.pv_load_p4ulv32"]
Control1 = "VVar"
Control2 = "None"
Control3 = "None"
pf = -0.95
pfMin = 0.9
pfMax = 1.05
Pmin = 0
Pmax = 1
uMin = 0.92
uDbMin = 0.967
uDbMax = 1.033
uMax = 1.07
QlimPU = 0.44
PFlim = 0.9
"Enable PF limit" = false
uMinC = 1.06
uMaxC = 1.1
PminVW = 10
VWtype = "Rated Power"
"%PCutin" = 0.1
"%PCutout" = 0.1
Efficiency = 100
Priority = "Var"
DampCoef = 0.8

["PVSystem.pv_load_p4ulv29"]
Control1 = "VVar"
Control2 = "None"
Control3 = "None"
pf = -0.95
pfMin = 0.9
pfMax = 1.05
Pmin = 0
Pmax = 1
uMin = 0.92
uDbMin = 0.967
uDbMax = 1.033
uMax = 1.07
QlimPU = 0.44
PFlim = 0.9
"Enable PF limit" = false
uMinC = 1.06
uMaxC = 1.1
PminVW = 10
VWtype = "Rated Power"
"%PCutin" = 0.1
"%PCutout" = 0.1
Efficiency = 100
Priority = "Var"
DampCoef = 0.8

["PVSystem.pv_load_p4ulv10"]
Control1 = "VVar"
Control2 = "None"
Control3 = "None"
pf = -0.95
pfMin = 0.9
pfMax = 1.05
Pmin = 0
Pmax = 1
uMin = 0.92
uDbMin = 0.967
uDbMax = 1.033
uMax = 1.07
QlimPU = 0.44
PFlim = 0.9
"Enable PF limit" = false
uMinC = 1.06
uMaxC = 1.1
PminVW = 10
VWtype = "Rated Power"
"%PCutin" = 0.1
"%PCutout" = 0.1
Efficiency = 100
Priority = "Var"
DampCoef = 0.8

["PVSystem.pv_load_p4ulv34"]
Control1 = "VVar"
Control2 = "None"
Control3 = "None"
pf = -0.95
pfMin = 0.9
pfMax = 1.05
Pmin = 0
Pmax = 1
uMin = 0.92
uDbMin = 0.967
uDbMax = 1.033
uMax = 1.07
QlimPU = 0.44
PFlim = 0.9
"Enable PF limit" = false
uMinC = 1.06
uMaxC = 1.1
PminVW = 10
VWtype = "Rated Power"
"%PCutin" = 0.1
"%PCutout" = 0.1
Efficiency = 100
Priority = "Var"
DampCoef = 0.8

["PVSystem.pv_load_p4ulv6"]
Control1 = "VVar"
Control2 = "None"
Control3 = "None"
pf = -0.95
pfMin = 0.9
pfMax = 1.05
Pmin = 0
Pmax = 1
uMin = 0.92
uDbMin = 0.967
uDbMax = 1.033
uMax = 1.07
QlimPU = 0.44
PFlim = 0.9
"Enable PF limit" = false
uMinC = 1.06
uMaxC = 1.1
PminVW = 10
VWtype = "Rated Power"
"%PCutin" = 0.1
"%PCutout" = 0.1
Efficiency = 100
Priority = "Var"
DampCoef = 0.8
