["Storage.storage_p4ulv10"]
VoltageMeaElem = "p4ulv10"
PowerMeaElem = "Line.l(r:p4udt9lv-p4ulv10)"
Control1 = "VVar"
Control2 = "PS"
Control3 = "None"
BaseLoadLim = 0
ExpWindowStart = "18:00:00"
ExpWindowEnd = "08:00:00"
Schedule = "[0, 0, -1, 0, 1, 0, 0]"
Days = 1
PS_lb = 0
PS_ub = 0
CF_dP_lb = -50
CF_dP_ub = 50
HrCharge = 2
HrDischarge = 15
"%rateCharge" = 100
"%rateDischarge" = 100
"%kWOut" = 50
pf = 1.0
pfMin = 0.8
pfMax = 1.05
Pmin = 0.25
Pmax = 1
uMin = 0.92
uDbMin = 0.967
uDbMax = 1.033
uMax = 1.07
QlimPU = 0.44
PFlim = 0.85
"Enable PF limit" = false
DampCoef = 0.8
alpha = 0.7
beta = 0
