[Loads]
Publish = [ "Powers", "VoltagesMagAng",]
NoPublish = []

[PVSystems]
Publish = []
NoPublish = [ "Powers", "VoltagesMagAng",]

[Storages]
Publish = []
NoPublish = [ "Powers", "VoltagesMagAng", "%stored",]

[Buses]
Publish = []
NoPublish = [ "puVmagAngle",]

[Circuits]
Publish = [ "TotalPower",]
NoPublish = [ "AllBusMagPu",]

[Lines]
Publish = []
NoPublish = [ "normamps", "CurrentsMagAng",]

[Transformers]
Publish = []
NoPublish = [ "normamps", "CurrentsMagAng", "taps",]
